openapi: 3.0.3
info:
  title: N8N M-Files API
  version: 1.0.0
  description: OpenAPI contract gegenereerd uit Postman collection
servers:
- url: https://example.invalid
paths:
  /mfiles/subproject:
    post:
      summary: create subproject IN BEWERKING
      responses:
        '200':
          description: Success
      requestBody:
        required: true
        content:
          application/json:
            example:
              Hoofdproject: Z00000
              Nummer: AA00000
              Omschrijving: Project omschrijving
              Onderdeel: onderdeel GUID (was Regio) - WORDT ALLEEN GEBRUIKT INDIEN
                HET HOOFDPROJECT NIET BESTAAT
              Verantwoordelijke1: Pietje Pukketje
              Verantwoordelijke2: Henk de Vries
              Verantwoordelijke3: Jan Janssen
              Verantwoordelijke4: Kaatje Puk
              Verantwoordelijke5: ''
              Plaats: Oldenzaal
    put:
      summary: update subproject HOP
      responses:
        '200':
          description: Success
      requestBody:
        required: true
        content:
          application/json:
            example:
              ClientID: oude call
              Method: wordt genegeerd
              ObjectGUID: '{99925761-CCDE-4BA6-8BF6-5163F869FBC1}'
              Nummer: Gewijzigde nummer
              Omschrijving: Gewijzigde naam
              Hoofdproject: wordt genegeerd
              Status: '{7184AE09-DAA8-4C2A-976E-5155D5E50921}'
              Regio: wordt genegeerd
              Uitvoeringstype: wordt genegeerd
              Bedrijfsleider: Jeroen Kloppers
              Teamleider: Frank Wolsink
              Werkvoorbereider: Harm Thuis
              Uitvoerder: Frank Wolsink
              Plaats: Gewijzigde plaats
              Gemeente: wordt genegeerd
              Projectreferentie: wordt genegeerd
              Kenmerk: wordt genegeerd
    get:
      summary: get subproject
      responses:
        '200':
          description: Success
      parameters:
      - name: nummer
        in: query
        required: false
        schema:
          type: string
        description: subprojectnummer
  /mfiles/dossier:
    post:
      summary: create dossier HOP
      responses:
        '200':
          description: Success
      requestBody:
        required: true
        content:
          application/json:
            example:
              ClientID: oude call
              Method: wordt genegeerd
              Code: dossiernummer
              Omschrijving: Gas - Gestuurde boring
              Project: '{E0E56B22-7656-4F4C-9575-094477A79D75}'
              Engineer: wordt genegeerd
              Discipline: Gas
              SoortWerk: wordt genegeerd
              Opdrachtgever: 100120 - Gemeente Amsterdam
              OGVerantwoordelijke: A. Peters - Contactpersoon
              OGInkoopcode: PO-778899 Externe Referentie
              Prijsboek: wordt genegeerd
    get:
      summary: get dossier
      responses:
        '200':
          description: Success
      parameters:
      - name: nummer
        in: query
        required: false
        schema:
          type: string
        description: nummer van het dossier
  /mfiles/url_subproject:
    post:
      summary: project url HOP
      responses:
        '200':
          description: Success
      requestBody:
        required: true
        content:
          application/json:
            example:
              ClientID: oude call
              Method: wordt genegeerd
              ObjectGUID: '{E0E56B22-7656-4F4C-9575-094477A79D75}'
    get:
      summary: project url
      responses:
        '200':
          description: Success
      parameters:
      - name: subprojectGUID
        in: query
        required: false
        schema:
          type: string
        description: GUID van het subproject
  /mfiles/url_dossier:
    post:
      summary: dossier url HOP
      responses:
        '200':
          description: Success
      requestBody:
        required: true
        content:
          application/json:
            example:
              ClientID: oude call
              Method: wordt genegeerd
              ObjectGUID: '{87878676-B41E-4C1E-87A5-BD3218E242CF}'
    get:
      summary: dossier url
      responses:
        '200':
          description: Success
      parameters:
      - name: dossierGUID
        in: query
        required: false
        schema:
          type: string
        description: GUID van het Dossier
  /mfiles/hoofdproject:
    get:
      summary: get hoofdproject
      responses:
        '200':
          description: Success
      parameters:
      - name: nummer
        in: query
        required: false
        schema:
          type: string
        description: nummer van het hoofdproject
